export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const SET_ID = 'SET_ID';
export const SET_NAME = 'SET_NAME';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_PRICE = 'SET_PRICE';
export const SET_URL = 'SET_URL';
export const SET_VALIDATION_STATE_PRICE = 'SET_VALIDATION_STATE_PRICE';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_ID = 'ADD_ID';
export const ADD_NAME = 'ADD_NAME';
export const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
export const ADD_PRICE = 'ADD_PRICE';
export const ADD_URL = 'ADD_URL';
export const ADD_VALIDATION_STATE_PRICE = 'ADD_VALIDATION_STATE_PRICE';

export const BASKET_ADD_PRODUCT = 'BASKET_ADD_PRODUCT';
export const BASKET_ADD_PRODUCT_ID = 'BASKET_ADD_PRODUCT_ID';
export const BASKET_SET_PRODUCT_IDS = 'BASKET_SET_PRODUCT_IDS';
export const BASKET_SET_PRODUCTS = 'BASKET_SET_PRODUCTS';

export const ADD_USER_EMAIL = 'ADD_USER_EMAIL';
export const ADD_USER_NAME = 'ADD_USER_NAME';
export const ADD_USER_PASSWORD = 'ADD_USER_PASSWORD';
export const ADD_USER_REPEAT_PASSWORD = 'ADD_USER_REPEAT_PASSWORD';
