export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';

export const SET_ID = 'SET_ID';
export const SET_NAME = 'SET_NAME';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_PRICE = 'SET_PRICE';
export const SET_URL = 'SET_URL';
export const SET_VALIDATION_STATE_PRICE = 'SET_VALIDATION_STATE_PRICE';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';

export const ADD_ID = 'ADD_ID';
export const ADD_NAME = 'ADD_NAME';
export const ADD_DESCRIPTION = 'ADD_DESCRIPTION';
export const ADD_PRICE = 'ADD_PRICE';
export const ADD_URL = 'ADD_URL';
export const ADD_VALIDATION_STATE_PRICE = 'ADD_VALIDATION_STATE_PRICE';

export const BASKET_ADD_PRODUCT = 'BASKET_ADD_PRODUCT';
export const BASKET_ADD_PRODUCT_ID = 'BASKET_ADD_PRODUCT_ID';
export const BASKET_SET_PRODUCT_IDS = 'BASKET_SET_PRODUCT_IDS';
export const BASKET_SET_PRODUCTS = 'BASKET_SET_PRODUCTS';

export const ADD_USER_EMAIL = 'ADD_USER_EMAIL';
export const ADD_USER_NAME = 'ADD_USER_NAME';
export const ADD_USER_PASSWORD = 'ADD_USER_PASSWORD';
export const ADD_USER_REPEAT_PASSWORD = 'ADD_USER_REPEAT_PASSWORD';

export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_PASSWORD = 'SET_USER_PASSWORD'; 
export const EMAIL_OR_PASSWORD_NOT_EXIST = 'EMAIL_OR_PASSWORD_NOT_EXIST'; 
export const SET_SIGN_UP_ERROR = 'SET_SIGN_UP_ERROR';

export const STOP_AUTHORIZATION_PROCESS = 'STOP_AUTHORIZATION_PROCESS';
export const START_AUTHORIZATION_PROCESS = 'START_AUTHORIZATION_PROCESS';
export const SET_AUTHORIZED_USER_DATA = 'SET_AUTHORIZED_USER_DATA';
export const SIGN_OUT = 'SIGN_OUT';

export const HEALTHY_FOOD_SET_SELECTED_DAY = 'HEALTHY_FOOD_SET_SELECTED_DAY';
export const HEALTHY_FOOD_SET_SELECTED_EATING_TIME_ITEM = 'HEALTHY_FOOD_SET_SELECTED_EATING_TIME_ITEM';
export const HEALTHY_FOOD_SET_NEW_EATING_TIME_ITEM_NAME = 'HEALTHY_FOOD_SET_NEW_EATING_TIME_ITEM_NAME';
export const HEALTHY_FOOD_SET_NEW_PRODUCT_NAME = 'HEALTHY_FOOD_SET_NEW_PRODUCT_NAME';
export const HEALTHY_FOOD_SET_NEW_PRODUCT_WEIGHT = 'HEALTHY_FOOD_SET_NEW_PRODUCT_WEIGHT';
export const HEALTHY_FOOD_UPDATE_DAY = 'HEALTHY_FOOD_UPDATE_DAY';
export const HEALTHY_FOOD_ADD_DAY = 'HEALTHY_FOOD_ADD_DAY';
